# Generated by Django 4.2.3 on 2023-07-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titile',
            new_name='title',
        ),
    ]
